require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BootScriptsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # BootScript. As you add validations to BootScript, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BootScriptsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all boot_scripts as @boot_scripts" do
      boot_script = BootScript.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:boot_scripts)).to eq([boot_script])
    end
  end

  describe "GET show" do
    it "assigns the requested boot_script as @boot_script" do
      boot_script = BootScript.create! valid_attributes
      get :show, {:id => boot_script.to_param}, valid_session
      expect(assigns(:boot_script)).to eq(boot_script)
    end
  end

  describe "GET new" do
    it "assigns a new boot_script as @boot_script" do
      get :new, {}, valid_session
      expect(assigns(:boot_script)).to be_a_new(BootScript)
    end
  end

  describe "GET edit" do
    it "assigns the requested boot_script as @boot_script" do
      boot_script = BootScript.create! valid_attributes
      get :edit, {:id => boot_script.to_param}, valid_session
      expect(assigns(:boot_script)).to eq(boot_script)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BootScript" do
        expect {
          post :create, {:boot_script => valid_attributes}, valid_session
        }.to change(BootScript, :count).by(1)
      end

      it "assigns a newly created boot_script as @boot_script" do
        post :create, {:boot_script => valid_attributes}, valid_session
        expect(assigns(:boot_script)).to be_a(BootScript)
        expect(assigns(:boot_script)).to be_persisted
      end

      it "redirects to the created boot_script" do
        post :create, {:boot_script => valid_attributes}, valid_session
        expect(response).to redirect_to(BootScript.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boot_script as @boot_script" do
        post :create, {:boot_script => invalid_attributes}, valid_session
        expect(assigns(:boot_script)).to be_a_new(BootScript)
      end

      it "re-renders the 'new' template" do
        post :create, {:boot_script => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested boot_script" do
        boot_script = BootScript.create! valid_attributes
        put :update, {:id => boot_script.to_param, :boot_script => new_attributes}, valid_session
        boot_script.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested boot_script as @boot_script" do
        boot_script = BootScript.create! valid_attributes
        put :update, {:id => boot_script.to_param, :boot_script => valid_attributes}, valid_session
        expect(assigns(:boot_script)).to eq(boot_script)
      end

      it "redirects to the boot_script" do
        boot_script = BootScript.create! valid_attributes
        put :update, {:id => boot_script.to_param, :boot_script => valid_attributes}, valid_session
        expect(response).to redirect_to(boot_script)
      end
    end

    describe "with invalid params" do
      it "assigns the boot_script as @boot_script" do
        boot_script = BootScript.create! valid_attributes
        put :update, {:id => boot_script.to_param, :boot_script => invalid_attributes}, valid_session
        expect(assigns(:boot_script)).to eq(boot_script)
      end

      it "re-renders the 'edit' template" do
        boot_script = BootScript.create! valid_attributes
        put :update, {:id => boot_script.to_param, :boot_script => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boot_script" do
      boot_script = BootScript.create! valid_attributes
      expect {
        delete :destroy, {:id => boot_script.to_param}, valid_session
      }.to change(BootScript, :count).by(-1)
    end

    it "redirects to the boot_scripts list" do
      boot_script = BootScript.create! valid_attributes
      delete :destroy, {:id => boot_script.to_param}, valid_session
      expect(response).to redirect_to(boot_scripts_url)
    end
  end

end
