require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CloudConfigsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CloudConfig. As you add validations to CloudConfig, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CloudConfigsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cloud_configs as @cloud_configs" do
      cloud_config = CloudConfig.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:cloud_configs)).to eq([cloud_config])
    end
  end

  describe "GET show" do
    it "assigns the requested cloud_config as @cloud_config" do
      cloud_config = CloudConfig.create! valid_attributes
      get :show, {:id => cloud_config.to_param}, valid_session
      expect(assigns(:cloud_config)).to eq(cloud_config)
    end
  end

  describe "GET new" do
    it "assigns a new cloud_config as @cloud_config" do
      get :new, {}, valid_session
      expect(assigns(:cloud_config)).to be_a_new(CloudConfig)
    end
  end

  describe "GET edit" do
    it "assigns the requested cloud_config as @cloud_config" do
      cloud_config = CloudConfig.create! valid_attributes
      get :edit, {:id => cloud_config.to_param}, valid_session
      expect(assigns(:cloud_config)).to eq(cloud_config)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CloudConfig" do
        expect {
          post :create, {:cloud_config => valid_attributes}, valid_session
        }.to change(CloudConfig, :count).by(1)
      end

      it "assigns a newly created cloud_config as @cloud_config" do
        post :create, {:cloud_config => valid_attributes}, valid_session
        expect(assigns(:cloud_config)).to be_a(CloudConfig)
        expect(assigns(:cloud_config)).to be_persisted
      end

      it "redirects to the created cloud_config" do
        post :create, {:cloud_config => valid_attributes}, valid_session
        expect(response).to redirect_to(CloudConfig.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cloud_config as @cloud_config" do
        post :create, {:cloud_config => invalid_attributes}, valid_session
        expect(assigns(:cloud_config)).to be_a_new(CloudConfig)
      end

      it "re-renders the 'new' template" do
        post :create, {:cloud_config => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cloud_config" do
        cloud_config = CloudConfig.create! valid_attributes
        put :update, {:id => cloud_config.to_param, :cloud_config => new_attributes}, valid_session
        cloud_config.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested cloud_config as @cloud_config" do
        cloud_config = CloudConfig.create! valid_attributes
        put :update, {:id => cloud_config.to_param, :cloud_config => valid_attributes}, valid_session
        expect(assigns(:cloud_config)).to eq(cloud_config)
      end

      it "redirects to the cloud_config" do
        cloud_config = CloudConfig.create! valid_attributes
        put :update, {:id => cloud_config.to_param, :cloud_config => valid_attributes}, valid_session
        expect(response).to redirect_to(cloud_config)
      end
    end

    describe "with invalid params" do
      it "assigns the cloud_config as @cloud_config" do
        cloud_config = CloudConfig.create! valid_attributes
        put :update, {:id => cloud_config.to_param, :cloud_config => invalid_attributes}, valid_session
        expect(assigns(:cloud_config)).to eq(cloud_config)
      end

      it "re-renders the 'edit' template" do
        cloud_config = CloudConfig.create! valid_attributes
        put :update, {:id => cloud_config.to_param, :cloud_config => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cloud_config" do
      cloud_config = CloudConfig.create! valid_attributes
      expect {
        delete :destroy, {:id => cloud_config.to_param}, valid_session
      }.to change(CloudConfig, :count).by(-1)
    end

    it "redirects to the cloud_configs list" do
      cloud_config = CloudConfig.create! valid_attributes
      delete :destroy, {:id => cloud_config.to_param}, valid_session
      expect(response).to redirect_to(cloud_configs_url)
    end
  end

end
